apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: autoverse-chroma-pvc
  namespace: autoverse-ai
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 500Mi
  
---

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: autoverse-onnx-pvc
  namespace: autoverse-ai
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 500Mi
